---
# tasks file for nginx_role

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy Customized Web Page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Nginx

